# Generated by Django 5.1.7 on 2025-03-31 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(blank=True, max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('contato', models.CharField(max_length=50)),
                ('descricao_servico', models.TextField(max_length=500)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
