# Generated by Django 5.1.7 on 2025-04-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_faixa_etaria_genero_agenda_imagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='proprietario',
            new_name='profissional',
        ),
    ]
