# Generated by Django 5.1.7 on 2025-04-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agenda_profissional_delete_profissional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='profissional',
            new_name='proprietario',
        ),
    ]
